production:
  adapter: redis
  url: redis://localhost:6379

staging:
  adapter: redis
  url: redis://localhost:6379

development:
  adapter: redis
  url: redis://localhost:6379

test:
  adapter: async
