
development:
  adapter: postgresql
  encoding: unicode
  database: opensimplif_development
  host: localhost
  pool: 5
  username: tps
  password: lol


test:
  adapter: postgresql
  encoding: unicode
  database: opensimplif_test<%= ENV['TEST_ENV_NUMBER'] %>
  host: localhost
  pool: 5
  username: tps
  password: lol


